name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 17 ]
        os: [ubuntu, windows]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test
